name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 'Docker Login to ACR'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/keshopifyliqpayappremix
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/keshopifyliqpayappremix
